<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ITHCJQB" failures="3" tests="3" name="Surefire test" time="2.263" errors="0" timestamp="2022-12-26T02:51:58 BRT">
  <testcase classname="TestSocket" name="calldog" time="0.01">
    <failure type="java.net.BindException" message="Address already in use: bind">
      <![CDATA[java.net.BindException: Address already in use: bind
at java.base/sun.nio.ch.Net.bind0(Native Method)
at java.base/sun.nio.ch.Net.bind(Net.java:555)
at java.base/sun.nio.ch.Net.bind(Net.java:544)
at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:629)
at java.base/java.net.ServerSocket.bind(ServerSocket.java:393)
at java.base/java.net.ServerSocket.<init>(ServerSocket.java:275)
at java.base/java.net.ServerSocket.<init>(ServerSocket.java:168)
at com.nixe.pinup.socket.ListingSOCKET.<init>(ListingSOCKET.java:23)
at TestSocket.calldog(TestSocket.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- calldog -->
  <testcase classname="TestSocket" name="initCliente" time="2.214">
    <failure type="java.net.ConnectException" message="Connection refused: connect">
      <![CDATA[java.net.ConnectException: Connection refused: connect
at java.base/sun.nio.ch.Net.connect0(Native Method)
at java.base/sun.nio.ch.Net.connect(Net.java:579)
at java.base/sun.nio.ch.Net.connect(Net.java:568)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:576)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:666)
at java.base/java.net.Socket.connect(Socket.java:600)
at java.base/java.net.Socket.<init>(Socket.java:509)
at java.base/java.net.Socket.<init>(Socket.java:289)
at TestSocket.initCliente(TestSocket.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- initCliente -->
  <testcase classname="TestSocket" name="testSocket" time="0.0">
    <failure type="java.net.BindException" message="Address already in use: bind">
      <![CDATA[java.net.BindException: Address already in use: bind
at java.base/sun.nio.ch.Net.bind0(Native Method)
at java.base/sun.nio.ch.Net.bind(Net.java:555)
at java.base/sun.nio.ch.Net.bind(Net.java:544)
at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:629)
at java.base/java.net.ServerSocket.bind(ServerSocket.java:393)
at java.base/java.net.ServerSocket.<init>(ServerSocket.java:275)
at java.base/java.net.ServerSocket.<init>(ServerSocket.java:168)
at com.nixe.pinup.socket.ListingSOCKET.<init>(ListingSOCKET.java:23)
at TestSocket.testSocket(TestSocket.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testSocket -->
</testsuite> <!-- Surefire test -->
